In [1]:
from operator import indexOf
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns
import matplotlib as mpl

from sklearn.model_selection import train_test_split
from sklearn.ensemble import RandomForestRegressor
from sklearn.metrics import mean_absolute_error
from sklearn.metrics import mean_squared_error
from sklearn.metrics import mean_squared_error
from sklearn import metrics

pd.set_option('display.max_columns', None)
# pd.set_option('display.max_rows', None)
# pd.set_option('display.max_colwidth',1000)

df_LIMPIO=pd.read_csv('data_NEW/df_LIMPIO.csv', index_col=0)
df_LIMPIO

,latitude,longitude,accommodates,bedrooms,beds,price,review_scores_rating,total_viviendas_host,reviews_per_month,amenities_len,room_type_code,eur_distrito,ranking,dist_p_sol,bathrooms_num,bathrooms_priv_or_shar,air_cond,elevator,price_per_month,price_per_year,host_since_years
0,40.45724,-3.67688,2,1.0,1.0,60.0,98.0,1,0.58,272,50,4508.0,67.220486,5.8,1.0,0,1,1,900.0,21900.0,13
1,40.40381,-3.74130,1,1.0,1.0,31.0,92.0,2,0.42,444,50,2287.0,47.008319,4.7,1.0,1,1,1,465.0,11315.0,12
2,40.38840,-3.69511,6,3.0,5.0,50.0,0.0,7,0.00,631,100,3917.0,55.025641,1.9,2.0,1,0,1,750.0,18250.0,12
3,40.42183,-3.70529,3,0.0,1.0,92.0,98.0,1,0.13,460,100,4503.0,68.043894,0.8,1.0,1,1,1,1380.0,33580.0,2
4,40.38975,-3.69018,1,1.0,1.0,26.0,94.0,1,1.12,215,50,3917.0,55.025641,1.9,1.0,1,0,1,390.0,9490.0,12
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19613,40.40756,-3.69937,1,1.0,1.0,23.0,0.0,8,0.00,229,50,4503.0,68.043894,0.8,2.0,0,0,0,345.0,8395.0,4
19614,40.43706,-3.71364,1,1.0,1.0,21.0,0.0,8,0.00,136,50,4855.0,64.056634,2.4,3.5,0,1,0,315.0,7665.0,4
19615,40.43857,-3.70715,1,1.0,1.0,22.0,0.0,8,0.00,327,50,4855.0,64.056634,2.4,3.0,1,0,0,330.0,8030.0,4
19616,40.43027,-3.66759,1,1.0,1.0,19.0,0.0,8,0.00,306,50,5328.0,74.694253,2.2,3.0,0,0,0,285.0,6935.0,4
19617,40.43484,-3.70667,1,1.0,2.0,20.0,0.0,8,0.00,116,50,4855.0,64.056634,2.4,3.0,0,0,0,300.0,7300.0,4

In [9]:
# ELIMINAR OUTLIERS LOQUÍSIMOS ES VERY VERY IMPORTANTE
import scipy.stats as stats
from scipy.stats import mstats


df_LIMPIO['price_per_year'] = stats.mstats.winsorize(df_LIMPIO['price_per_year'], limits=[None, 0.4])
# df_LIMPIO['price_per_year'] = np.log1p(df_LIMPIO['price_per_year'])

In [10]:
X=df_LIMPIO.drop(columns=[
                        ## VARIABLES TARGET
                        'price',
                        'price_per_month',
                        'price_per_year',

                        ## VARIABLES PREDICTORAS ÚTILES
                        # 'latitude',
                        # 'longitude',
                        # 'accommodates',
                        # 'bedrooms',
                        'beds',
                        'amenities_len',
                        # 'room_type_code',
                        'eur_distrito',
                        'Ranking',
                        'dist_p_sol',
                        # 'bathrooms_num',
                        # 'bathrooms_priv_or_shar',
                        'facturas_inc',
                        'pet',
                        'airport',
                        'lux',
                        'breakfast',
                        'wifi',
                        'pool',
                        # 'air_cond',
                        # 'elevator',
                        'balcony',
                        'workspace',
                        'nespresso',
                        'single_level',

                        ## DATOS SOBRE HOST Y REVIEWS
                        'reviews_per_month',
                        'review_scores_rating',
                        'host_since'
                        # 'total_viviendas_host',
 ])
        
y=df_LIMPIO['price_per_year']

features = list(X)

X_train, X_test, y_train, y_test = train_test_split(X,
                                                    y,
                                                    test_size = 0.20,
                                                    random_state=42)

In [11]:
# prueba = X_test
nueva_fila = {'latitude':40.403002,
            'longitude': -3.690574,
            'accommodates': 3,
            'bedrooms': 2,
            'total_viviendas_host': 2,
            'room_type_code': 100,
            'bathrooms_num':1,
            'bathrooms_priv_or_shar': 1,
            'air_cond': 1,
            'elevator': 1
            }

prueba= X_test.append(nueva_fila, ignore_index=True)

streamlit_test = prueba[-1:]
streamlit_test

,latitude,longitude,accommodates,bedrooms,total_viviendas_host,room_type_code,bathrooms_num,bathrooms_priv_or_shar,air_cond,elevator
3924,40.403002,-3.690574,3.0,2.0,2.0,100.0,1.0,1.0,1.0,1.0

In [12]:
streamlit_test.to_csv('data_NEW/streamlit_test.csv')

In [13]:
modelo_streamlit = RandomForestRegressor(
            n_estimators = 450,
            criterion    = 'squared_error',
            max_depth    = 50,
            max_features = 4,
            oob_score    = False,
            n_jobs       = -1,
            random_state = 123
            )
            
modelo_streamlit.fit(X_train, y_train)

predictions_rf = modelo_streamlit.predict(X_test)

print('MAE:', mean_absolute_error(y_test, predictions_rf))
# print('MSE:', mean_squared_error(y_test, predictions_rf))
# print('RMSE:', np.sqrt(mean_squared_error(y_test, predictions_rf)))

print(modelo_streamlit.score(X_train, y_train))
print(modelo_streamlit.score(X_test, y_test))

MAE: 1597.7819863826285
0.9428066002681065
0.5927427760324723

In [14]:
import pickle

filename = 'Modelo_STREAMLITE'

with open(filename, 'wb') as archivo_salida:
    pickle.dump(modelo_streamlit, archivo_salida)